name: Deploy latest version

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout latest master
      uses: actions/checkout@master
    - name: Touch src/config.js
      run: |
        cp ./src/config.js.bak ./src/config.js &&
        sed -i 's/API-KEY-HERE/${{ secrets.API_KEY }}/' ./src/config.js &&
        sed -i 's/MAPBOX-API-KEY-HERE/${{ secrets.MAPBOX_API_KEY }}/' ./src/config.js
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: '13.x'
    - name: npm install and build
      run: |
        npm ci
        npm run build --if-present
      env:
        CI: true
    - name: Deploy to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1'
        SOURCE_DIR: './build'